rm(list = ls())
gc()

source("R/simulate.R")
source("R/estimateEM.R")
source("R/init_EM.R")
source("R/E_step.R")
source("R/M_step.R")
source("R/shutoff.R")
source("R/generic_functions.R")
source("R/shifts_manipulations.R")
source("R/plot_functions.R")
source("R/parsimonyNumber.R")
source("R/partitionsNumber.R")
source("R/model_selection.R")
sourceCpp("src/upward_downward.cpp")

datestamp <- format(Sys.time(), "%Y-%m-%d")

save.image(paste0("../../../Bastide_These/Rapports/data/all_functions_", datestamp, ".RData"))
