// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// create_model
Rcpp::List create_model(arma::mat const& Delta, arma::mat const& Variance, arma::vec const& edge_length, arma::umat ed, int i);
RcppExport SEXP PhylogeneticEM_create_model(SEXP DeltaSEXP, SEXP VarianceSEXP, SEXP edge_lengthSEXP, SEXP edSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat const& >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Variance(VarianceSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type ed(edSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    __result = Rcpp::wrap(create_model(Delta, Variance, edge_length, ed, i));
    return __result;
END_RCPP
}
// upward_test
Rcpp::List upward_test(arma::mat const& data, arma::umat const& ed, int i);
RcppExport SEXP PhylogeneticEM_upward_test(SEXP dataSEXP, SEXP edSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat const& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::umat const& >::type ed(edSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    __result = Rcpp::wrap(upward_test(data, ed, i));
    return __result;
END_RCPP
}
// upward_downward_BM
Rcpp::List upward_downward_BM(arma::mat const& data, arma::umat const& ed, arma::mat const& Delta, arma::mat const& Variance, arma::vec const& edge_length, Rcpp::List root_state_list);
RcppExport SEXP PhylogeneticEM_upward_downward_BM(SEXP dataSEXP, SEXP edSEXP, SEXP DeltaSEXP, SEXP VarianceSEXP, SEXP edge_lengthSEXP, SEXP root_state_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat const& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::umat const& >::type ed(edSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Variance(VarianceSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type root_state_list(root_state_listSEXP);
    __result = Rcpp::wrap(upward_downward_BM(data, ed, Delta, Variance, edge_length, root_state_list));
    return __result;
END_RCPP
}
// upward_downward_OU
Rcpp::List upward_downward_OU(arma::mat const& data, arma::umat const& ed, arma::mat const& Beta, arma::mat const& Stationary_Var, arma::vec const& edge_length, arma::mat const& Alpha, Rcpp::List root_state_list);
RcppExport SEXP PhylogeneticEM_upward_downward_OU(SEXP dataSEXP, SEXP edSEXP, SEXP BetaSEXP, SEXP Stationary_VarSEXP, SEXP edge_lengthSEXP, SEXP AlphaSEXP, SEXP root_state_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat const& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::umat const& >::type ed(edSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Beta(BetaSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Stationary_Var(Stationary_VarSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Alpha(AlphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type root_state_list(root_state_listSEXP);
    __result = Rcpp::wrap(upward_downward_OU(data, ed, Beta, Stationary_Var, edge_length, Alpha, root_state_list));
    return __result;
END_RCPP
}
// log_likelihood
double log_likelihood(arma::mat const& data, arma::umat const& ed, arma::mat const& Delta, arma::mat const& Variance, arma::vec const& edge_length, Rcpp::List const& root_state_list);
RcppExport SEXP PhylogeneticEM_log_likelihood(SEXP dataSEXP, SEXP edSEXP, SEXP DeltaSEXP, SEXP VarianceSEXP, SEXP edge_lengthSEXP, SEXP root_state_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat const& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< arma::umat const& >::type ed(edSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type Variance(VarianceSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type edge_length(edge_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::List const& >::type root_state_list(root_state_listSEXP);
    __result = Rcpp::wrap(log_likelihood(data, ed, Delta, Variance, edge_length, root_state_list));
    return __result;
END_RCPP
}
